### ISSUE TITLE
Format method does not exist in facade.

### ISSUE THREAD

**Issue by mseymour** [BlueBayTravel/Dosh#2]
If I initialize Dosh (just like in the README) and try to format a number, it says that it cannot find the method in DoshFacade. Laravel 5.1.

**Comment by jbrooksuk** [comment]
Hey @mseymour, in the README, the top example is using the `Dosh` class itself.

If you want to use the facade, then you simply do `Dosh::format()`.

**Comment by mseymour** [comment]
Now I get this:
```
syntax error, unexpected 'TRY' (T_TRY), expecting identifier (T_STRING)
…/­vendor/­bluebaytravel/­dosh/­src/­Dosh.php:63
```

**Comment by jbrooksuk** [comment]
`TRY` was removed https://github.com/BlueBayTravel/Dosh/commit/732a2e8bd94edb46d4ea76a8f819d9369014bced due to the error you had. Are you running the latest version?

**Comment by mseymour** [comment]
I'm using dev-master. Composer will not add the dependency if I only call `composer require bluebaytravel/dosh`.

**Comment by jbrooksuk** [comment]
I'll tag a v1.0.0 release tomorrow.
